### ISSUE TITLE
Laravel Documentation is incorrect

### ISSUE THREAD

**Issue by firecentaur** [pestphp/docs#125]
Hi there, in the Laravel Dusk example, the example code does not work:
https://pestphp.com/docs/plugins/laravel

use Laravel\Dusk\Browser;
```
 <?php
it('has homepage', function () {
    $this->browse(function (Browser $browser) {
        $browser->visit('/')
            ->assertSee('Pest');
    });
});
```

This yields an error Call to undefined method Tests\Feature\UserFormCreateTest::browse()

**Comment by owenvoke** [comment]
Just to check, your `UserFormCreateTest` class is extending the `Tests\DuskTestCase` class?
