### ISSUE TITLE
--ansi flag?

### ISSUE THREAD

**Issue by backtrackjack** [pestphp/docs#200]
Hello,

I'm unsure of this `--ansi` flag demonstrated in the bitbucket pipelines CI/CD example in the docs: https://pestphp.com/docs/continuous-integration#content-example-with-bitbucket-pipelines

can't find any documentation on it, and it certainly doesn't work when used. Is anyone able to provide some context please? Hope this is the right place to ask :)

![CleanShot 2023-07-04 at 09 41 02](https://github.com/pestphp/docs/assets/87053124/859c60aa-3e15-4326-8cdd-9940f37bc69d)

**Comment by devajmeireles** [comment]
> Hello,
> 
> I'm unsure of this `--ansi` flag demonstrated in the bitbucket pipelines CI/CD example in the docs: https://pestphp.com/docs/continuous-integration#content-example-with-bitbucket-pipelines
> 
> can't find any documentation on it, and it certainly doesn't work when used. Is anyone able to provide some context please? Hope this is the right place to ask :)
> 
> ![CleanShot 2023-07-04 at 09 41 02](https://user-images.githubusercontent.com/87053124/250694740-859c60aa-3e15-4326-8cdd-9940f37bc69d.png)

Hey! @backtrackjack . Thanks for your report.

I've opened #216 to remove that.
