### ISSUE TITLE
Docs for pest v1

### ISSUE THREAD

**Issue by pedrogxv** [pestphp/docs#238]
Hello, so I'm working on a project where the php version is 7.3 and I saw that pest v1 supports it on the composer.json, we need to make some test so I'm thinking in use pest, but in the official docs I could only see documents of the most recent pest version.

I think it would be nice to have the option to choose between version of pest in the docs, what do you think?

I've used pest v1 and v2 a time ago and I love the framework.

**Comment by nunomaduro** [comment]
Right. You can check the history of the documentation on this repository. For the Pest v3 / v2, we will keep the v2 documentation on the website.
